/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '23.10.2016 14:09' with Gradle 3.1
 *
 * @author root, @date 23.10.2016 14:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
